[package]
name = "home_assist_main"
version = "0.1.0"
edition = "2024"
publish = false

[[bin]]
name = "home_assist"
path = "src/main.rs"

[dependencies]
rppal = "0.22.1"
reqwest = { version = "0.13", features = ["json"] }
serde = { version = "1.0", features = ["derive"] }
either = "1.17.0"
url = "2.5.8"
thiserror = "2.0.20"
dotenvy = "0.15.7"
