export component App inherits Window {
    background: #1e1e1eff;
    width: 128px;
    height: 160px;

    in property <string> date_str: "26/08/26";
    in property <string> time_str: "09:00";
    in property <int> solar_est_wh: 0;
    in property <int> usage_est_wh: 0;
    in property <float> home_soc_percent: 67.0;
    in property <float> ev_soc_percent: 67.0;
    in property <int> home_soc_min: 0;
    in property <int> home_soc_max: 100;
    in property <bool> tariff: false;
    

    id_1-4512 := Rectangle { /* LCD */
        width: 128px;
        height: 160px;
        x: 0px;
        y: 0px;
        background: #ffffffff;
        clip: true;
        id_1-4515 := Rectangle { /* TopBar */
            width: 128px;
            height: 20px;
            x: 0px;
            y: 0px;
            background: #fff4a4ff;
            clip: true;
            id_1-4526 := Rectangle { /* DateTime */
                width: 108px;
                height: 20px;
                x: 0px;
                y: 0px;
                clip: true;
                id_5-11 := Rectangle { /* Date */
                    width: 64px;
                    height: 20px;
                    x: 0px;
                    y: 0px;
                    clip: true;
                    id_5-6 := Text { /* DateField */
                        width: 64px;
                        height: 20px;
                        x: 0px;
                        y: 0px;
                        text: root.date_str;
                        font-family: "DejaVu Sans";
                        font-size: 12px;
                        font-weight: 400;
                        horizontal-alignment: center;
                        vertical-alignment: center;
                        letter-spacing: 0px;
                        color: #000000ff;
                    }
                }
                id_5-10 := Rectangle { /* Time */
                    width: 44px;
                    height: 20px;
                    x: 64px;
                    y: 0px;
                    clip: true;
                    id_5-2 := Text { /* TimeField */
                        width: 44px;
                        height: 20px;
                        x: 0px;
                        y: 0px;
                        text: root.time_str;
                        font-family: "DejaVu Sans";
                        font-size: 12px;
                        font-weight: 400;
                        horizontal-alignment: center;
                        vertical-alignment: center;
                        letter-spacing: 0px;
                        color: #000000ff;
                    }
                }
            }
            id_14-7 := Rectangle { /* StateIcon */
                width: 20px;
                height: 20px;
                x: 108px;
                y: 0px;
                clip: true;
                id_I5-57_7758-12329 := Path { /* Icon */
                    width: 18px;
                    height: 18px;
                    x: 1px;
                    y: 1px;
                    commands: "M9 5.5 A3.5 3.5 0 1 0 9.01 5.5 M9 2 L9 3.5 M9 14.5 L9 16 M2 9 L3.5 9 M14.5 9 L16 9 M4.05 4.05 L5.11 5.11 M12.89 12.89 L13.95 13.95 M4.05 13.95 L5.11 12.89 M12.89 5.11 L13.95 4.05";
                    stroke: #1e1e1eff;
                    stroke-width: 1.5px;
                    visible: !tariff;
                }
                id_I5-58_7758-11944 := Path { /* Icon */
                    width: 14px;
                    height: 14px;
                    x: 3px;
                    y: 3px;
                    commands: "M12 7.5 A4.5 4.5 0 1 1 5.8 2 A3.6 3.6 0 0 0 12 7.5 Z";
                    stroke: #1e1e1eff;
                    stroke-width: 1.5px;
                    visible: tariff;
                }
            }
        }
        id_1-4528 := Rectangle { /* PVInfo */
            width: 128px;
            height: 36px;
            x: 0px;
            y: 20px;
            background: #c1ffe6ff;
            clip: true;
            id_1-4529 := Rectangle { /* SolarSection */
                width: 64px;
                height: 36px;
                x: 0px;
                y: 0px;
                clip: true;
                id_6-65 := Text { /* Label */
                    width: 64px;
                    height: 18px;
                    x: 0px;
                    y: 0px;
                    text: "Solar Est:";
                    font-family: "DejaVu Sans";
                    font-size: 12px;
                    font-weight: 400;
                    horizontal-alignment: center;
                    vertical-alignment: center;
                    letter-spacing: 0px;
                    color: #000000ff;
                }
                id_6-63 := Text { /* SolarEstField */
                    width: 64px;
                    height: 18px;
                    x: 0px;
                    y: 18px;
                    text: "\{root.solar_est_wh}Wh";
                    font-family: "DejaVu Sans";
                    font-size: 12px;
                    font-weight: 400;
                    horizontal-alignment: center;
                    vertical-alignment: center;
                    letter-spacing: 0px;
                    color: #000000ff;
                }
            }
            id_1-4530 := Rectangle { /* UsageSection */
                width: 64px;
                height: 36px;
                x: 64px;
                y: 0px;
                clip: true;
                id_5-51 := Text { /* Label */
                    width: 64px;
                    height: 18px;
                    x: 0px;
                    y: 0px;
                    text: "Usage Est:";
                    font-family: "DejaVu Sans";
                    font-size: 12px;
                    font-weight: 400;
                    horizontal-alignment: center;
                    vertical-alignment: center;
                    letter-spacing: 0px;
                    color: #000000ff;
                }
                id_5-52 := Text { /* UsageEstField */
                    width: 64px;
                    height: 18px;
                    x: 0px;
                    y: 18px;
                    text: "\{root.usage_est_wh}Wh";
                    font-family: "DejaVu Sans";
                    font-size: 12px;
                    font-weight: 400;
                    horizontal-alignment: center;
                    vertical-alignment: center;
                    letter-spacing: 0px;
                    color: #000000ff;
                }
            }
        }
        id_1-4514 := Rectangle { /* SoCSection */
            width: 128px;
            height: 56px;
            x: 0px;
            y: 56px;
            background: #c1c4faff;
            clip: true;
            id_1-4522 := Rectangle { /* SoCInfo */
                width: 128px;
                height: 20px;
                x: 0px;
                y: 0px;
                clip: true;
                id_9-122 := Text { /* Label */
                    width: 120px;
                    height: 20px;
                    x: 4px;
                    y: 0px;
                    text: "Home Battery SoC:";
                    font-family: "DejaVu Sans";
                    font-size: 12px;
                    font-weight: 400;
                    horizontal-alignment: center;
                    vertical-alignment: center;
                    letter-spacing: 0px;
                    color: #000000ff;
                }
            }
            id_9-120 := Rectangle { /* BarSection */
                width: 128px;
                height: 36px;
                x: 0px;
                y: 20px;
                clip: true;
                id_6-61 := Text { /* MinField */
                    width: 32px;
                    height: 18px;
                    x: 0px;
                    y: 0px;
                    text: "\{root.home_soc_min}%";
                    font-family: "DejaVu Sans";
                    font-size: 12px;
                    font-weight: 400;
                    horizontal-alignment: center;
                    vertical-alignment: center;
                    letter-spacing: 0px;
                    color: #000000ff;
                }
                id_9-124 := Text { /* MaxField */
                    width: 32px;
                    height: 18px;
                    x: 96px;
                    y: 0px;
                    text: "\{root.home_soc_max}%";
                    font-family: "DejaVu Sans";
                    font-size: 12px;
                    font-weight: 400;
                    horizontal-alignment: center;
                    vertical-alignment: center;
                    letter-spacing: 0px;
                    color: #000000ff;
                }
                id_9-91 := Rectangle { /* SoCBar */
                    width: 128px;
                    height: 18px;
                    x: 0px;
                    y: 18px;
                    clip: true;
                    id_9-87 := Rectangle { /* ChargeBar */
                        width: 128px;
                        height: 18px;
                        x: 0px;
                        y: 0px;
                        clip: true;
                        id_9-88 := Rectangle { /* Charge */
                            width: (Math.max(root.home_soc_percent, 22.0) / 100.0) * parent.width;
                            height: 18px;
                            x: 0px;
                            y: 0px;
                            background: #135e18ff;
                            clip: true;
                            id_9-89 := Text { /* MinLabel */
                                width: parent.width - 4px;
                                height: 18px;
                                x: 0px;
                                y: 0px;
                                text: "\{Math.round(root.home_soc_percent)}%";
                                font-family: "DejaVu Sans";
                                font-size: 12px;
                                font-weight: 400;
                                horizontal-alignment: right;
                                vertical-alignment: center;
                                letter-spacing: 0px;
                                color: #fae4e4ff;
                            }
                        }
                    }
                }
            }
        }
        id_1-4532 := Rectangle { /* EVSection */
            width: 128px;
            height: 48px;
            x: 0px;
            y: 112px;
            background: #cee6bfff;
            clip: true;
            id_1-4534 := Rectangle { /* EVInfo */
                width: 128px;
                height: 30px;
                x: 0px;
                y: 0px;
                clip: true;
                id_9-84 := Text { /* Label */
                    width: 120px;
                    height: 30px;
                    x: 4px;
                    y: 0px;
                    text: "EV SoC:";
                    font-family: "DejaVu Sans";
                    font-size: 12px;
                    font-weight: 400;
                    horizontal-alignment: center;
                    vertical-alignment: bottom;
                    letter-spacing: 0px;
                    color: #000000ff;
                }
            }
            id_I9-115_9-87 := Rectangle { /* ChargeBar */
                width: 128px;
                height: 18px;
                x: 0px;
                y: 30px;
                clip: true;
                id_I9-115_9-88 := Rectangle { /* Charge */
                    width: (Math.max(root.ev_soc_percent, 22.0) / 100.0) * parent.width;
                    height: 18px;
                    x: 0px;
                    y: 0px;
                    background: #135e18ff;
                    clip: true;
                    id_I9-115_9-89 := Text { /* MinLabel */
                        width: parent.width - 4px;
                        height: 18px;
                        x: 0px;
                        y: 0px;
                        text: "\{Math.round(root.ev_soc_percent)}%";
                        font-family: "DejaVu Sans";
                        font-size: 12px;
                        font-weight: 400;
                        horizontal-alignment: right;
                        vertical-alignment: center;
                        letter-spacing: 0px;
                        color: #fae4e4ff;
                    }
                }
            }
        }
    }
}